### ISSUE TITLE
process.env.GITHUB_TOKEN  is required？

### ISSUE THREAD

**Issue by lopins** [kamranahmedse/github-pages-blog-action#5]
```
[gh-pages (root-commit) 15f590b] [Action GitHub Pages Blog] Prepare blog
 10 files changed, 1615 insertions(+)
 create mode 100644 .gitkep
 create mode 100644 .nojekyll
 create mode 100644 404.html
 create mode 100644 CNAME
 create mode 100644 about.html
 create mode 100644 behavior-of-links-created-using-javascript.html
 create mode 100644 css/normalize.css
 create mode 100644 css/theme.css
 create mode 100644 img/guard.gif
 create mode 100644 index.html
/usr/bin/git push origin gh-pages --force
remote: Permission to lopins/lopins.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/lopins/lopins.github.io.git/': The requested URL returned error: [40](https://github.com/lopins/lopins.github.io/actions/runs/10775786227/job/29881007128#step:3:41)3

/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:[46](https://github.com/lopins/lopins.github.io/actions/runs/10775786227/job/29881007128#step:3:47)9:1)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

https://github.com/kamranahmedse/github-pages-blog-action/blob/14a6b4526adb015afff2dedfad12c1405784cb9c/src/main.ts#L8

**Comment by lopins** [comment]
> ```
> [gh-pages (root-commit) 15f590b] [Action GitHub Pages Blog] Prepare blog
>  10 files changed, 1615 insertions(+)
>  create mode 100644 .gitkep
>  create mode 100644 .nojekyll
>  create mode 100644 404.html
>  create mode 100644 CNAME
>  create mode 100644 about.html
>  create mode 100644 behavior-of-links-created-using-javascript.html
>  create mode 100644 css/normalize.css
>  create mode 100644 css/theme.css
>  create mode 100644 img/guard.gif
>  create mode 100644 index.html
> /usr/bin/git push origin gh-pages --force
> remote: Permission to lopins/lopins.github.io.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/lopins/lopins.github.io.git/': The requested URL returned error: [40](https://github.com/lopins/lopins.github.io/actions/runs/10775786227/job/29881007128#step:3:41)3
> 
> /home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:592
>                 error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
> ^
> Error: The process '/usr/bin/git' failed with exit code 128
>     at ExecState._setResult (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
>     at ExecState.CheckComplete (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/lopins/github-pages-blog-action/v0.0.11/webpack:/@kamranahmedse/github-pages-blog-action/node_modules/@actions/exec/lib/toolrunner.js:[46](https://github.com/lopins/lopins.github.io/actions/runs/10775786227/job/29881007128#step:3:47)9:1)
>     at ChildProcess.emit (node:events:519:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
> ```
> 
> https://github.com/kamranahmedse/github-pages-blog-action/blob/14a6b4526adb015afff2dedfad12c1405784cb9c/src/main.ts#L8

![5847641448](https://github.com/user-attachments/assets/3c98f729-2db5-461f-92eb-655de5a4df41)

It has been resolved. [readme.md#L29](https://github.com/lopins/github-pages-blog-action/blob/8e07c71efbb64e3d9657cb14b8ab1641f2594cd0/readme.md?plain=1#L29)
